package exercisesdb.model;

import exercisesdb.model.base.BaseBookCatalog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookCatalog extends BaseBookCatalog<BookCatalog> {
	public static final BookCatalog dao = new BookCatalog().dao();
}
