package exercisesdb.model;

import exercisesdb.model.base.BaseExamAbi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamAbi extends BaseExamAbi<ExamAbi> {
	public static final ExamAbi dao = new ExamAbi().dao();
}
