package exercisesdb.model;

import exercisesdb.model.base.BaseExam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exam extends BaseExam<Exam> {
	public static final Exam dao = new Exam().dao();
}
