package exercisesdb.model;

import exercisesdb.model.base.BaseExamKind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamKind extends BaseExamKind<ExamKind> {
	public static final ExamKind dao = new ExamKind().dao();
}
