package exercisesdb.model;

import exercisesdb.model.base.BaseExamKp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamKp extends BaseExamKp<ExamKp> {
	public static final ExamKp dao = new ExamKp().dao();
}
