package exercisesdb.model;

import exercisesdb.model.base.BaseKnowPoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnowPoint extends BaseKnowPoint<KnowPoint> {
	public static final KnowPoint dao = new KnowPoint().dao();
}
