package exercisesdb.model;

import com.alibaba.fastjson.JSONObject;
import exercisesdb.common.LongId;
import exercisesdb.model.base.BaseMyPaper;
import exercisesdb.types.MyPaperStructs;

import javax.annotation.PostConstruct;
import java.util.Date;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MyPaper extends BaseMyPaper<MyPaper> {
	public static final MyPaper dao = new MyPaper().dao();

	public MyPaper(){

	}
	public MyPaper(MyPaperStructs myPaperStructs){
		if(myPaperStructs.getId()!= null){
			setId(myPaperStructs.getId());
		}else{
			setId(LongId.getId());
		}
		setUserId(myPaperStructs.getUserId());
		setCaption(myPaperStructs.getCaption());
		setSection(myPaperStructs.getSection());
		setSubjectId(myPaperStructs.getSubjectId());
		setGrade(myPaperStructs.getGradeId());
		setScope(myPaperStructs.getScope());
		setTimeLen(myPaperStructs.getTimeLen());
		setPerson(myPaperStructs.getPerson());
		setTotal(myPaperStructs.getTotal());
		setState(myPaperStructs.getState());
//		setFinished(new Date());
		setData(JSONObject.toJSONString(myPaperStructs.getData()));
	}
//   private String subjectName;
//
//	public void setSubjectName(String subjectName){
//		this.subjectName = subjectName;
//	}
//	public String getSubjectName(){
//		return this.subjectName;
//	}
//    protected Map<String,Object> getAttrs(){
//        Map<String,Object> attrs=super._getAttrs();
//        attrs.put("subjectName",this.getSubjectName());
//        return attrs;
//    }

}
