package exercisesdb.model;

import exercisesdb.model.base.BasePaperExam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaperExam extends BasePaperExam<PaperExam> {
	public static final PaperExam dao = new PaperExam().dao();
}
