package exercisesdb.model;

import exercisesdb.model.base.BasePaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Paper extends BasePaper<Paper> {
	public static final Paper dao = new Paper().dao();
}
