package exercisesdb.model;

import exercisesdb.model.base.BaseSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subject extends BaseSubject<Subject> {
	public static final Subject dao = new Subject().dao();
}
