package exercisesdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.util.Date;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMyPaper<M extends BaseMyPaper<M>> extends Model<M> implements IBean {

    public M setId(Long ngId) {
        set("ng_id", ngId);
        return (M) this;
    }

    public Long getId() {
        return getLong("ng_id");
    }

    public M setUserId(Long ngUserId) {
        set("ng_user_id", ngUserId);
        return (M) this;
    }

    public Long getUserId() {
        return getLong("ng_user_id");
    }

    public M setCaption(String szCaption) {
        set("sz_caption", szCaption);
        return (M) this;
    }

    public String getCaption() {
        return getStr("sz_caption");
    }

    public M setSection(Integer ntSection) {
        set("nt_section", ntSection);
        return (M) this;
    }

    public Integer getSection() {
        return getInt("nt_section");
    }

    public M setSubjectId(Long ngSubjectId) {
        set("ng_subject_id", ngSubjectId);
        return (M) this;
    }

    public Long getSubjectId() {
        return getLong("ng_subject_id");
    }

    public M setGrade(Integer ntGrade) {
        set("nt_grade", ntGrade);
        return (M) this;
    }

    public Integer getGrade() {
        return getInt("nt_grade");
    }

    public M setScope(String szScope) {
        set("sz_scope", szScope);
        return (M) this;
    }

    public String getScope() {
        return getStr("sz_scope");
    }

    public M setTimeLen(String szTimeLen) {
        set("sz_time_len", szTimeLen);
        return (M) this;
    }

    public String getTimeLen() {
        return getStr("sz_time_len");
    }

    public M setPerson(String szPerson) {
        set("sz_person", szPerson);
        return (M) this;
    }

    public String getPerson() {
        return getStr("sz_person");
    }

    public M setTotal(Integer ntTotal) {
        set("nt_total", ntTotal);
        return (M) this;
    }

    public Integer getTotal() {
        return getInt("nt_total");
    }

    public M setData(String txData) {
        set("tx_data", txData);
        return (M) this;
    }

    public String getData() {
        return getStr("tx_data");
    }

    public M setState(Integer ntState) {
        set("nt_state", ntState);
        return (M) this;
    }

    public Integer getState() {
        return getInt("nt_state");
    }

    public M setFinished(java.util.Date date) {
        set("ts_finished", date);
        return (M) this;
    }

    public java.util.Date getFinished() {
        return getDate("ts_finished");
    }

    public M setFileStore(String fileStore) {
        set("sz_file_store", fileStore);
        return (M) this;
    }

    public String getFileStore() {
        return getStr("sz_file_store");
    }

    public M setTitleBar(Integer titleBar) {
        set("nt_title_bar", titleBar);
        return (M) this;
    }

    public Integer getTitleBar() {
        return getInt("nt_title_bar");
    }

    public M setPaperInfo(Integer paperInfo) {
        set("nt_info_bar", paperInfo);
        return (M) this;
    }

    public Integer getPaperInfo() {
        return getInt("nt_info_bar");
    }

    public M setInputInfo(Integer inputInfo) {
        set("nt_input_bar", inputInfo);
        return (M) this;
    }

    public Integer getInputInfo() {
        return getInt("nt_input_bar");
    }

    public M setTongfen(Integer tongfen) {
        set("nt_tongfen_bar", tongfen);
        return (M) this;
    }

    public Integer getTongfen() {
        return getInt("nt_tongfen_bar");
    }

    public M setPingfen(Integer pingfen) {
        set("nt_pingfen_bar", pingfen);
        return (M) this;
    }

    public Integer getPingfen() {
        return getInt("nt_pingfen_bar");
    }

    public M setShowAnswer(Integer showAnswer) {
        set("nt_show_answer", showAnswer);
        return (M) this;
    }

    public Integer getShowAnswer() {
        return getInt("nt_show_answer");
    }

    public M setShowDefen(Integer showDefen) {
        set("nt_show_defen", showDefen);
        return (M) this;
    }

    public Integer getShowDefen() {
        return getInt("nt_show_defen");
    }

    public M setFileKind(Integer fileKind) {
        set("nt_file_kind", fileKind);
        return (M) this;
    }

    public Integer getFileKind() {
        return getInt("nt_file_kind");
    }

    public M setPageSize(Integer pageSize) {
        set("nt_page_size", pageSize);
        return (M) this;
    }

    public Integer getPageSize() {
        return getInt("nt_page_size");
    }

}
