package exercisesdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

    public M setId(Long ngId) {
        set("ng_id", ngId);
        return (M) this;
    }

    public Long getId() {
        return getLong("ng_id");
    }

    public M setUsername(String szUsername) {
        set("sz_username", szUsername);
        return (M) this;
    }

    public String getUsername() {
        return getStr("sz_username");
    }

    public M setPassword(String szPassword) {
        set("sz_password", szPassword);
        return (M) this;
    }

    public String getPassword() {
        return getStr("sz_password");
    }

    public M setSection(Integer ntSection) {
        set("nt_section", ntSection);
        return (M) this;
    }

    public Integer getSection() {
        return getInt("nt_section");
    }

    public M setSubjectId(Long ngSubjectId) {
        set("ng_subject_id", ngSubjectId);
        return (M) this;
    }

    public Long getSubjectId() {
        return getLong("ng_subject_id");
    }

    public M setNickname(String szNickname) {
        set("sz_nickname", szNickname);
        return (M) this;
    }

    public String getNickname() {
        return getStr("sz_nickname");
    }

}
