package exercisesdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaperExam<M extends BasePaperExam<M>> extends Model<M> implements IBean {

	public M setId(Long ngId) {
		set("ng_id", ngId);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("ng_id");
	}

	public M setPaperId(Long ngPaperId) {
		set("ng_paper_id", ngPaperId);
		return (M)this;
	}
	
	public Long getPaperId() {
		return getLong("ng_paper_id");
	}

	public M setExamId(Long ngExamId) {
		set("ng_exam_id", ngExamId);
		return (M)this;
	}
	
	public Long getExamId() {
		return getLong("ng_exam_id");
	}

	public M setIndex(Integer ntIndex) {
		set("nt_index", ntIndex);
		return (M)this;
	}
	
	public Integer getIndex() {
		return getInt("nt_index");
	}

	public M setKind(String szKind) {
		set("sz_kind", szKind);
		return (M)this;
	}
	
	public String getKind() {
		return getStr("sz_kind");
	}

	public M setComment(String txComment) {
		set("tx_comment", txComment);
		return (M)this;
	}
	
	public String getComment() {
		return getStr("tx_comment");
	}

}
