package exercisesdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFavorite<M extends BaseFavorite<M>> extends Model<M> implements IBean {

	public M setId(Long ngId) {
		set("ng_id", ngId);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("ng_id");
	}

	public M setUserId(Long ngUserId) {
		set("ng_user_id", ngUserId);
		return (M)this;
	}
	
	public Long getUserId() {
		return getLong("ng_user_id");
	}

	public M setSection(Integer ntSection) {
		set("nt_section", ntSection);
		return (M)this;
	}
	
	public Integer getSection() {
		return getInt("nt_section");
	}

	public M setSubjectId(Integer ngSubjectId) {
		set("ng_subject_id", ngSubjectId);
		return (M)this;
	}
	
	public Integer getSubjectId() {
		return getInt("ng_subject_id");
	}

	public M setExamId(Long ngExamId) {
		set("ng_exam_id", ngExamId);
		return (M)this;
	}
	
	public Long getExamId() {
		return getLong("ng_exam_id");
	}

	public M setTimeCreated(java.util.Date tsCreated) {
		set("ts_created", tsCreated);
		return (M)this;
	}
	
	public java.util.Date getTimeCreated() {
		return get("ts_created");
	}

}
