package exercisesdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExamKp<M extends BaseExamKp<M>> extends Model<M> implements IBean {

	public M setId(Long ngId) {
		set("ng_id", ngId);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("ng_id");
	}

	public M setExamId(Long ngExamId) {
		set("ng_exam_id", ngExamId);
		return (M)this;
	}
	
	public Long getExamId() {
		return getLong("ng_exam_id");
	}

	public M setKpId(Long ngKpId) {
		set("ng_kp_id", ngKpId);
		return (M)this;
	}
	
	public Long getKpId() {
		return getLong("ng_kp_id");
	}

}
