package exercisesdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaper<M extends BasePaper<M>> extends Model<M> implements IBean {

    public M setId(Long ngId) {
        set("ng_id", ngId);
        return (M) this;
    }

    public Long getId() {
        return getLong("ng_id");
    }

    public M setNum(String szNum) {
        set("sz_num", szNum);
        return (M) this;
    }

    public String getNum() {
        return getStr("sz_num");
    }

    public M setCaption(String szCaption) {
        set("sz_caption", szCaption);
        return (M) this;
    }

    public String getCaption() {
        return getStr("sz_caption");
    }

    public M setKind(String szKind) {
        set("sz_kind", szKind);
        return (M) this;
    }

    public String getKind() {
        return getStr("sz_kind");
    }

    public M setAge(String szAge) {
        set("sz_age", szAge);
        return (M) this;
    }

    public String getAge() {
        return getStr("sz_age");
    }

    public M setCatId(Long ngCatId) {
        set("ng_cat_id", ngCatId);
        return (M) this;
    }

    public Long getCatId() {
        return getLong("ng_cat_id");
    }

    public M setSubjectId(Long ngSubjectId) {
        set("ng_subject_id", ngSubjectId);
        return (M) this;
    }

    public Long getSubjectId() {
        return getLong("ng_subject_id");
    }

    public M setWenli(String szWenli) {
        set("sz_wenli", szWenli);
        return (M) this;
    }

    public String getWenli() {
        return getStr("sz_wenli");
    }

    public M setProv(String szProv) {
        set("sz_prov", szProv);
        return (M) this;
    }

    public String getProv() {
        return getStr("sz_prov");
    }

    public M setCity(String szCity) {
        set("sz_city", szCity);
        return (M) this;
    }

    public String getCity() {
        return getStr("sz_city");
    }

    public M setTerm(Integer ntTerm) {
        set("nt_term", ntTerm);
        return (M) this;
    }

    public Integer getTerm() {
        return getInt("nt_term");
    }

    public M setGrade(Integer ntGrade) {
        set("nt_grade", ntGrade);
        return (M) this;
    }

    public Integer getGrade() {
        return getInt("nt_grade");
    }

    public M setScore(Integer ntScore) {
        set("nt_score", ntScore);
        return (M) this;
    }

    public Integer getScore() {
        return getInt("nt_score");
    }

    public M setScoreEx(Integer ntScoreEx) {
        set("nt_score_ex", ntScoreEx);
        return (M) this;
    }

    public Integer getScoreEx() {
        return getInt("nt_score_ex");
    }

    public M setCostResp(Integer ntCostResp) {
        set("nt_cost_resp", ntCostResp);
        return (M) this;
    }

    public Integer getCostResp() {
        return getInt("nt_cost_resp");
    }

    public M setTimeCreated(java.util.Date tsCreated) {
        set("ts_created", tsCreated);
        return (M) this;
    }

    public java.util.Date getTimeCreated() {
        return get("ts_created");
    }

    public M setTimeUpdated(java.util.Date tsUpdated) {
        set("ts_updated", tsUpdated);
        return (M) this;
    }

    public java.util.Date getTimeUpdated() {
        return get("ts_updated");
    }

    public M setTimeAuditing(java.util.Date tsAuditing) {
        set("ts_auditing", tsAuditing);
        return (M) this;
    }

    public java.util.Date getTimeAuditing() {
        return get("ts_auditing");
    }

    public M setTimeComment(String txComment) {
        set("tx_comment", txComment);
        return (M) this;
    }

    public String getTimeComment() {
        return getStr("tx_comment");
    }

    public M setInforSrc(String szInforSrc) {
        set("sz_infor_src", szInforSrc);
        return (M) this;
    }

    public String getInforSrc() {
        return getStr("sz_infor_src");
    }

    public M setInforKind(String szInforKind) {
        set("sz_infor_kind", szInforKind);
        return (M) this;
    }

    public String getInforKind() {
        return getStr("sz_infor_kind");
    }

    public M setOldId(Integer ntOldId) {
        set("nt_old_id", ntOldId);
        return (M) this;
    }

    public Integer getOldId() {
        return getInt("nt_old_id");
    }

}
