package exercisesdb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExam<M extends BaseExam<M>> extends Model<M> implements IBean {

	public M setId(Long ngId) {
		set("ng_id", ngId);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("ng_id");
	}

	public M setParentId(Long ngParentId) {
		set("ng_parent_id", ngParentId);
		return (M)this;
	}
	
	public Long getParentId() {
		return getLong("ng_parent_id");
	}

	public M setSubIndex(Integer ntSubIndex) {
		set("nt_sub_index", ntSubIndex);
		return (M)this;
	}
	
	public Integer getSubIndex() {
		return getInt("nt_sub_index");
	}

	public M setCatId(Long ngCatId) {
		set("ng_cat_id", ngCatId);
		return (M)this;
	}
	
	public Long getCatId() {
		return getLong("ng_cat_id");
	}

	public M setCatFull(String szCatFull) {
		set("sz_cat_full", szCatFull);
		return (M)this;
	}
	
	public String getCatFull() {
		return getStr("sz_cat_full");
	}

	public M setGrade(Integer ntGrade) {
		set("nt_grade", ntGrade);
		return (M)this;
	}
	
	public Integer getGrade() {
		return getInt("nt_grade");
	}

	public M setTerm(Integer ntTerm) {
		set("nt_term", ntTerm);
		return (M)this;
	}
	
	public Integer getTerm() {
		return getInt("nt_term");
	}

	public M setDeep(Integer ntDeep) {
		set("nt_deep", ntDeep);
		return (M)this;
	}
	
	public Integer getDeep() {
		return getInt("nt_deep");
	}

	public M setProv(String szProv) {
		set("sz_prov", szProv);
		return (M)this;
	}
	
	public String getProv() {
		return getStr("sz_prov");
	}

	public M setCity(String szCity) {
		set("sz_city", szCity);
		return (M)this;
	}
	
	public String getCity() {
		return getStr("sz_city");
	}

	public M setInforSrc(String szInforSrc) {
		set("sz_infor_src", szInforSrc);
		return (M)this;
	}
	
	public String getInforSrc() {
		return getStr("sz_infor_src");
	}

	public M setAge(String szAge) {
		set("sz_age", szAge);
		return (M)this;
	}
	
	public String getAge() {
		return getStr("sz_age");
	}

	public M setInforKind(String szInforKind) {
		set("sz_infor_kind", szInforKind);
		return (M)this;
	}
	
	public String getInforKind() {
		return getStr("sz_infor_kind");
	}

	public M setReadTime(Integer ntReadTime) {
		set("nt_read_time", ntReadTime);
		return (M)this;
	}
	
	public Integer getReadTime() {
		return getInt("nt_read_time");
	}

	public M setAnswerTime(Integer ntAnswerTime) {
		set("nt_answer_time", ntAnswerTime);
		return (M)this;
	}
	
	public Integer getAnswerTime() {
		return getInt("nt_answer_time");
	}

	public M setScore(Integer ntScore) {
		set("nt_score", ntScore);
		return (M)this;
	}
	
	public Integer getScore() {
		return getInt("nt_score");
	}

	public M setWenli(String szWenli) {
		set("sz_wenli", szWenli);
		return (M)this;
	}
	
	public String getWenli() {
		return getStr("sz_wenli");
	}

	public M setMust(String szMust) {
		set("sz_must", szMust);
		return (M)this;
	}
	
	public String getMust() {
		return getStr("sz_must");
	}

	public M setObjective(Integer ntObjective) {
		set("nt_objective", ntObjective);
		return (M)this;
	}
	
	public Integer getObjective() {
		return getInt("nt_objective");
	}

	public M setInforTrans(Integer ntInforTrans) {
		set("nt_infor_trans", ntInforTrans);
		return (M)this;
	}
	
	public Integer getInforTrans() {
		return getInt("nt_infor_trans");
	}

	public M setChartKind(String szChartKind) {
		set("sz_chart_kind", szChartKind);
		return (M)this;
	}
	
	public String getChartKind() {
		return getStr("sz_chart_kind");
	}

	public M setInPaper(Integer ntInPaper) {
		set("nt_in_paper", ntInPaper);
		return (M)this;
	}
	
	public Integer getInPaper() {
		return getInt("nt_in_paper");
	}

	public M setPaperNum(String szPaperNum) {
		set("sz_paper_num", szPaperNum);
		return (M)this;
	}
	
	public String getPaperNum() {
		return getStr("sz_paper_num");
	}

	public M setPagerLevel(String szPagerLevel) {
		set("sz_pager_level", szPagerLevel);
		return (M)this;
	}
	
	public String getPagerLevel() {
		return getStr("sz_pager_level");
	}

	public M setPaperAge(String szPaperAge) {
		set("sz_paper_age", szPaperAge);
		return (M)this;
	}
	
	public String getPaperAge() {
		return getStr("sz_paper_age");
	}

	public M setPaperIndex(String szPaperIndex) {
		set("sz_paper_index", szPaperIndex);
		return (M)this;
	}
	
	public String getPaperIndex() {
		return getStr("sz_paper_index");
	}

	public M setKeywords(String txKeywords) {
		set("tx_keywords", txKeywords);
		return (M)this;
	}
	
	public String getKeywords() {
		return getStr("tx_keywords");
	}

	public M setListen(String szListen) {
		set("sz_listen", szListen);
		return (M)this;
	}
	
	public String getListen() {
		return getStr("sz_listen");
	}

	public M setViewTimes(Integer ntViewTimes) {
		set("nt_view_times", ntViewTimes);
		return (M)this;
	}
	
	public Integer getViewTimes() {
		return getInt("nt_view_times");
	}

	public M setUsingTimes(Integer ntUsingTimes) {
		set("nt_using_times", ntUsingTimes);
		return (M)this;
	}
	
	public Integer getUsingTimes() {
		return getInt("nt_using_times");
	}

	public M setTimeCreated(java.util.Date tsCreated) {
		set("ts_created", tsCreated);
		return (M)this;
	}
	
	public java.util.Date getTimeCreated() {
		return get("ts_created");
	}

	public M setTimeUpdated(java.util.Date tsUpdated) {
		set("ts_updated", tsUpdated);
		return (M)this;
	}
	
	public java.util.Date getTimeUpdated() {
		return get("ts_updated");
	}

	public M setTimeAuditing(java.util.Date tsAuditing) {
		set("ts_auditing", tsAuditing);
		return (M)this;
	}
	
	public java.util.Date getTimeAuditing() {
		return get("ts_auditing");
	}

	public M setAudit(Integer ntAudit) {
		set("nt_audit", ntAudit);
		return (M)this;
	}
	
	public Integer getAudit() {
		return getInt("nt_audit");
	}

	public M setState(Integer ntState) {
		set("nt_state", ntState);
		return (M)this;
	}
	
	public Integer getState() {
		return getInt("nt_state");
	}

	public M setComment(String txComment) {
		set("tx_comment", txComment);
		return (M)this;
	}
	
	public String getComment() {
		return getStr("tx_comment");
	}

	public M setKpCap2(String szKpCap2) {
		set("sz_kp_cap2", szKpCap2);
		return (M)this;
	}
	
	public String getKpCap2() {
		return getStr("sz_kp_cap2");
	}

	public M setComment2(String txComment2) {
		set("tx_comment2", txComment2);
		return (M)this;
	}
	
	public String getComment2() {
		return getStr("tx_comment2");
	}

	public M setErrDescr(String txErrDescr) {
		set("tx_err_descr", txErrDescr);
		return (M)this;
	}
	
	public String getErrDescr() {
		return getStr("tx_err_descr");
	}

	public M setOldTextbook(String szOldTextbook) {
		set("sz_old_textbook", szOldTextbook);
		return (M)this;
	}
	
	public String getOldTextbook() {
		return getStr("sz_old_textbook");
	}

	public M setChapter(String szChapter) {
		set("sz_chapter", szChapter);
		return (M)this;
	}
	
	public String getChapter() {
		return getStr("sz_chapter");
	}

	public M setSegment(String szSegment) {
		set("sz_segment", szSegment);
		return (M)this;
	}
	
	public String getSegment() {
		return getStr("sz_segment");
	}

	public M setEdition(String szEdition) {
		set("sz_edition", szEdition);
		return (M)this;
	}
	
	public String getEdition() {
		return getStr("sz_edition");
	}

	public M setKindId(Long ngKindId) {
		set("ng_kind_id", ngKindId);
		return (M)this;
	}
	
	public Long getKindId() {
		return getLong("ng_kind_id");
	}

	public M setKindName(String szKindName) {
		set("sz_kind_name", szKindName);
		return (M)this;
	}
	
	public String getKindName() {
		return getStr("sz_kind_name");
	}

	public M setAbiCap(String szAbiCap) {
		set("sz_abi_cap", szAbiCap);
		return (M)this;
	}
	
	public String getAbiCap() {
		return getStr("sz_abi_cap");
	}

	public M setKpCap(String szKpCap) {
		set("sz_kp_cap", szKpCap);
		return (M)this;
	}
	
	public String getKpCap() {
		return getStr("sz_kp_cap");
	}

	public M setMingTi(String txMingti) {
		set("tx_mingti", txMingti);
		return (M)this;
	}
	
	public String getMingTi() {
		return getStr("tx_mingti");
	}

	public M setAnswer(String txAnswer) {
		set("tx_answer", txAnswer);
		return (M)this;
	}
	
	public String getAnswer() {
		return getStr("tx_answer");
	}

	public M setXuanXiang(String txXuanxiang) {
		set("tx_xuanxiang", txXuanxiang);
		return (M)this;
	}
	
	public String getXuanXiang() {
		return getStr("tx_xuanxiang");
	}

	public M setJieXi(String txJiexi) {
		set("tx_jiexi", txJiexi);
		return (M)this;
	}
	
	public String getJieXi() {
		return getStr("tx_jiexi");
	}

	public M setTiGan(String txTigan) {
		set("tx_tigan", txTigan);
		return (M)this;
	}
	
	public String getTiGan() {
		return getStr("tx_tigan");
	}

}
