package exercisesdb.config;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import exercisesdb.model.*;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {
	public static void mapping(ActiveRecordPlugin arp) {

		arp.addMapping("sys_ability_t", "ng_id", Ability.class);
		arp.addMapping("sys_book_catalog_t", "ng_id", BookCatalog.class);
		arp.addMapping("sys_exam_abi_t", "ng_id", ExamAbi.class);
		arp.addMapping("sys_exam_kind_t", "ng_id", ExamKind.class);
		arp.addMapping("sys_exam_kp_t", "ng_id", ExamKp.class);
		arp.addMapping("sys_exam_t", "ng_id", Exam.class);
		arp.addMapping("sys_favorite_t", "ng_id", Favorite.class);
		arp.addMapping("sys_know_point_t", "ng_id", KnowPoint.class);
		arp.addMapping("sys_my_paper_t", "ng_id", MyPaper.class);
		arp.addMapping("sys_paper_exam_t", "ng_id", PaperExam.class);
		arp.addMapping("sys_paper_t", "ng_id", Paper.class);
		arp.addMapping("sys_subject_t", "ng_id", Subject.class);
		arp.addMapping("sys_user_t", "ng_id", User.class);
	}
}

